[advisories]
yanked = "warn"
ignore = [
    "RUSTSEC-2021-0145",
    "RUSTSEC-2024-0336"
]

[licenses]
unlicensed = "warn"
allow = ["Apache-2.0", "MIT", "ISC", "Unicode-DFS-2016"]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
