name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get install -y lld
      - name: Build
        run: cargo build --release
